spring.application.name=demo

# Configuración del puerto del servidor
server.port=8080

# Configuración de H2 Database (En memoria)
spring.datasource.url=jdbc:h2:mem:techconfdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Habilitar la consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Crear el esquema automáticamente y ejecutar data.sql después
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true